import { 
  SeniorProfile, 
  Relationship, 
  Medication, 
  MedicationEvent, 
  DailyCheckIn, 
  Doctor, 
  Appointment, 
  HospitalPharmacy, 
  CommunityPost, 
  VoiceReply, 
  FamilyMessage, 
  CareTask, 
  HandoverReport, 
  AuditEvent 
} from '../domain/types';

export const initialSeniorProfile: SeniorProfile = {
  id: 'senior-01',
  fullName: 'Kavita Sharma',
  preferredName: 'Mom Sharma',
  age: 72,
  birthYear: 1954,
  avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=180&auto=format&fit=crop&q=80',
  bloodGroup: 'B+',
  allergies: ['Penicillin', 'Sulfa drugs'],
  chronicConditions: ['Hypertension', 'Mild Osteoarthritis'],
  pairingCode: '582-914',
  isPaired: true,
  address: {
    line1: 'B-402, Shanti Vihar Apartments',
    city: 'New Delhi',
    state: 'Delhi',
    postalCode: '110024',
    latitude: 28.5672,
    longitude: 77.2433,
  },
  emergencyContactIds: ['rel-01', 'rel-02', 'rel-03'],
  ayushmanCardNumber: 'AB-DEL-2024-998124',
  primaryDoctorId: 'doc-01',
};

export const initialRelationships: Relationship[] = [
  {
    id: 'rel-01',
    seniorId: 'senior-01',
    userId: 'user-priya',
    userName: 'Priya Sharma',
    userAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=180&auto=format&fit=crop&q=80',
    relationType: 'DAUGHTER',
    displayName: 'Priya (Daughter)',
    phone: '+91 98112 34567',
    isPrimaryContact: true,
    canManageMedications: true,
    canViewHealthRecords: true,
    canReceiveSOS: true,
    accessGrantedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'rel-02',
    seniorId: 'senior-01',
    userId: 'user-rohan',
    userName: 'Rohan Sharma',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=180&auto=format&fit=crop&q=80',
    relationType: 'SON',
    displayName: 'Rohan (Son)',
    phone: '+91 98223 45678',
    isPrimaryContact: false,
    canManageMedications: true,
    canViewHealthRecords: true,
    canReceiveSOS: true,
    accessGrantedAt: '2026-01-12T14:30:00Z',
  },
  {
    id: 'rel-03',
    seniorId: 'senior-01',
    userId: 'user-sunita',
    userName: 'Nurse Sunita Devi',
    userAvatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=180&auto=format&fit=crop&q=80',
    relationType: 'PROFESSIONAL_CAREGIVER',
    displayName: 'Sunita (Day Caregiver)',
    phone: '+91 98334 56789',
    isPrimaryContact: false,
    canManageMedications: true,
    canViewHealthRecords: false,
    canReceiveSOS: true,
    accessGrantedAt: '2026-03-01T08:00:00Z',
  },
];

export const initialMedications: Medication[] = [
  {
    id: 'med-01',
    seniorId: 'senior-01',
    name: 'Amlodipine 5mg',
    dosage: '1 tablet (5mg)',
    timingLabel: 'Morning (After Breakfast)',
    scheduledTime: '08:30',
    instructions: 'Take with warm water after eating breakfast',
    shape: 'ROUND',
    colorCode: '#197278',
    stockCount: 24,
    refillThreshold: 5,
    prescribedBy: 'Dr. Arvind Mehta',
  },
  {
    id: 'med-02',
    seniorId: 'senior-01',
    name: 'Shelcal 500 (Calcium + D3)',
    dosage: '1 tablet',
    timingLabel: 'Afternoon (After Lunch)',
    scheduledTime: '13:30',
    instructions: 'Take after lunch with milk or water',
    shape: 'OVAL',
    colorCode: '#F4F1E9',
    stockCount: 18,
    refillThreshold: 4,
    prescribedBy: 'Dr. Shalini Verma',
  },
  {
    id: 'med-03',
    seniorId: 'senior-01',
    name: 'Telmisartan 40mg',
    dosage: '1 tablet (40mg)',
    timingLabel: 'Night (After Dinner)',
    scheduledTime: '20:30',
    instructions: 'Take 30 minutes before sleep with water',
    shape: 'ROUND',
    colorCode: '#17324D',
    stockCount: 6,
    refillThreshold: 5,
    prescribedBy: 'Dr. Arvind Mehta',
  },
];

export const initialMedicationEvents: MedicationEvent[] = [
  {
    id: 'ev-01',
    medicationId: 'med-01',
    seniorId: 'senior-01',
    medicationName: 'Amlodipine 5mg',
    scheduledTime: '08:30',
    timestamp: '2026-09-15T08:32:00Z',
    status: 'TAKEN',
    recordedByRole: 'OLDER_ADULT',
    recordedByName: 'Kavita Sharma',
  },
  {
    id: 'ev-02',
    medicationId: 'med-02',
    seniorId: 'senior-01',
    medicationName: 'Shelcal 500',
    scheduledTime: '13:30',
    status: 'PENDING',
    recordedByRole: 'OLDER_ADULT',
    recordedByName: 'Kavita Sharma',
  },
  {
    id: 'ev-03',
    medicationId: 'med-03',
    seniorId: 'senior-01',
    medicationName: 'Telmisartan 40mg',
    scheduledTime: '20:30',
    status: 'PENDING',
    recordedByRole: 'OLDER_ADULT',
    recordedByName: 'Kavita Sharma',
  },
  // Yesterday's event for adherence calculation
  {
    id: 'ev-04',
    medicationId: 'med-03',
    seniorId: 'senior-01',
    medicationName: 'Telmisartan 40mg',
    scheduledTime: '20:30',
    timestamp: '2026-09-14T20:45:00Z',
    status: 'TAKEN',
    recordedByRole: 'OLDER_ADULT',
    recordedByName: 'Kavita Sharma',
  },
];

export const initialCheckIn: DailyCheckIn = {
  id: 'chk-01',
  seniorId: 'senior-01',
  date: '2026-09-15',
  timestamp: new Date(Date.now() - 34 * 60 * 1000).toISOString(), // 34 mins ago
  mood: 'GOOD',
  moodLabel: 'Feeling Good 😊',
  respondedByRole: 'OLDER_ADULT',
};

export const initialDoctors: Doctor[] = [
  {
    id: 'doc-01',
    fullName: 'Dr. Arvind Mehta',
    specialty: 'Senior Cardiologist',
    hospitalName: 'Max Super Speciality Hospital, Saket',
    phone: '+91 98100 11223',
    availableDays: 'Mon, Wed, Fri (10:00 AM – 2:00 PM)',
  },
  {
    id: 'doc-02',
    fullName: 'Dr. Shalini Verma',
    specialty: 'Consultant Orthopedic & Joint Care',
    hospitalName: 'Fortis Escorts Heart Institute',
    phone: '+91 98200 33445',
    availableDays: 'Tue, Thu, Sat (11:00 AM – 4:00 PM)',
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: 'appt-01',
    seniorId: 'senior-01',
    doctorId: 'doc-01',
    doctorName: 'Dr. Arvind Mehta',
    specialty: 'Cardiology Review & ECG',
    hospitalName: 'Max Super Speciality Hospital, Saket',
    dateTime: '2026-09-17T11:00:00Z', // Thursday 11:00 AM
    purpose: 'Routine 6-month blood pressure review and ECG check',
    accompaniedBy: 'Rohan Sharma (Son)',
    isCompleted: false,
  },
];

export const initialHospitalsPharmacies: HospitalPharmacy[] = [
  {
    id: 'hp-01',
    name: 'Max Super Speciality Hospital',
    type: 'HOSPITAL',
    address: '1, 2, Press Enclave Marg, Saket, New Delhi',
    distanceKm: 2.1,
    phone: '011 2651 5050',
    openHours: '24x7 Emergency & Trauma',
    isEmergency24x7: true,
  },
  {
    id: 'hp-02',
    name: 'Apollo Pharmacy — Lajpat Nagar',
    type: 'PHARMACY',
    address: 'Shop 14, Central Market, Lajpat Nagar II, New Delhi',
    distanceKm: 0.6,
    phone: '011 2984 7654',
    openHours: 'Open 24 Hours • Free Home Delivery',
    isEmergency24x7: true,
  },
  {
    id: 'hp-03',
    name: 'Fortis C-Doc Center of Excellence',
    type: 'HOSPITAL',
    address: 'B-16, Chirag Enclave, New Delhi',
    distanceKm: 3.4,
    phone: '011 4910 1222',
    openHours: '24x7 Emergency & OPD',
    isEmergency24x7: true,
  },
];

export const initialCommunityPost: CommunityPost = {
  id: 'post-01',
  date: '2026-09-15',
  topicTitle: 'Monsoon Memories & Childhood Rains',
  topicPrompt: 'What is your favorite memory of monsoon with your family? Tap to listen to friends or share your memory.',
  category: 'MEMORIES',
  audioDurationSec: 42,
  featuredStoryBy: 'Meena ji (Bengaluru)',
  featuredStoryAudioText: 'When it rained in our childhood home, Ma would make hot onion pakoras and ginger cardamom chai. We would all sit on the veranda watching the rain wash the mango tree leaves clean.',
  voiceRepliesCount: 14,
};

export const initialVoiceReplies: VoiceReply[] = [
  {
    id: 'reply-01',
    postId: 'post-01',
    authorName: 'Suresh Kumar',
    authorCity: 'Pune',
    durationSec: 36,
    createdAt: '2026-09-15T09:15:00Z',
    transcription: 'We used to make small paper boats with my elder brother and float them in the street water. Such simple happiness that was!',
  },
  {
    id: 'reply-02',
    postId: 'post-01',
    authorName: 'Shakuntala Devi',
    authorCity: 'Jaipur',
    durationSec: 48,
    createdAt: '2026-09-15T10:40:00Z',
    transcription: 'The smell of wet soil after the first rain in Rajasthan is unforgettable. We would play songs and prepare kachoris together.',
  },
];

export const initialFamilyMessages: FamilyMessage[] = [
  {
    id: 'fmsg-01',
    seniorId: 'senior-01',
    senderName: 'Priya Sharma',
    senderRelation: 'Daughter',
    senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=180&auto=format&fit=crop&q=80',
    type: 'VOICE_NOTE',
    durationSec: 18,
    textMessage: 'Good morning Mom! I hope you had your morning tea and took your medicine. Aarav says he will call you after school today!',
    sentAt: '2026-09-15T07:45:00Z',
    listenedBySenior: true,
    listenedAt: '2026-09-15T08:15:00Z',
  },
  {
    id: 'fmsg-02',
    seniorId: 'senior-01',
    senderName: 'Aarav (Grandson)',
    senderRelation: 'Grandson',
    senderAvatar: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=180&auto=format&fit=crop&q=80',
    type: 'PHOTO',
    contentUrl: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=80',
    textMessage: 'Dadi, look at the painting of our mango tree I made for you!',
    sentAt: '2026-09-14T17:20:00Z',
    listenedBySenior: true,
    listenedAt: '2026-09-14T18:00:00Z',
  },
];

export const initialCareTasks: CareTask[] = [
  {
    id: 'task-01',
    residentId: 'senior-01',
    residentName: 'Kavita Sharma',
    roomNumber: 'Room 402',
    caregiverId: 'user-sunita',
    title: 'Administer Morning BP Medication & Log Blood Pressure',
    category: 'MEDICATION',
    scheduledTime: '08:30 AM',
    status: 'COMPLETED',
    completedAt: '08:35 AM',
    vitalsData: {
      bloodPressure: '126/80',
      pulse: 74,
    },
  },
  {
    id: 'task-02',
    residentId: 'senior-01',
    residentName: 'Kavita Sharma',
    roomNumber: 'Room 402',
    caregiverId: 'user-sunita',
    title: 'Supervise Afternoon Calcium Pill & Hydration Check',
    category: 'MEDICATION',
    scheduledTime: '01:30 PM',
    status: 'DUE_NOW',
  },
  {
    id: 'task-03',
    residentId: 'res-02',
    residentName: 'R. K. Verma',
    roomNumber: 'Room 405',
    caregiverId: 'user-sunita',
    title: 'Assisted Garden Mobility Walk (20 Minutes)',
    category: 'MOBILITY',
    scheduledTime: '10:00 AM',
    status: 'COMPLETED',
    completedAt: '10:25 AM',
  },
  {
    id: 'task-04',
    residentId: 'res-03',
    residentName: 'Malti Rao',
    roomNumber: 'Room 408',
    caregiverId: 'user-sunita',
    title: 'Pre-Lunch Blood Glucose Fasting Check',
    category: 'VITALS',
    scheduledTime: '12:00 PM',
    status: 'COMPLETED',
    completedAt: '12:05 PM',
    vitalsData: {
      bloodSugar: 118,
    },
    concernNote: 'Resident mentioned slight dizziness when standing up quickly.',
  },
  {
    id: 'task-05',
    residentId: 'senior-01',
    residentName: 'Kavita Sharma',
    roomNumber: 'Room 402',
    caregiverId: 'user-sunita',
    title: 'Evening Vitals Check (BP & SpO2) & Assist with Dinner',
    category: 'VITALS',
    scheduledTime: '06:30 PM',
    status: 'PENDING',
  },
];

export const initialHandoverReport: HandoverReport = {
  id: 'handover-01',
  shiftName: 'Day Shift (08:00 – 16:00)',
  date: '2026-09-15',
  outgoingCaregiverName: 'Nurse Sunita Devi',
  incomingCaregiverName: 'Nurse Rajesh Yadav',
  completedCount: 8,
  pendingCount: 2,
  concernsCount: 1,
  completedItems: [
    'Mrs. Kavita Sharma (402): Morning BP 126/80 mmHg logged. Amlodipine 5mg given at 08:35 AM.',
    'Mr. R. K. Verma (405): Completed 20 min morning garden walk. Mood pleasant.',
    'Mrs. Malti Rao (408): Fasting glucose checked (118 mg/dL). Lunch completed.',
  ],
  pendingItems: [
    'Mrs. Kavita Sharma (402): Physiotherapy knee exercise due at 15:00 PM.',
    'Mr. O. P. Gupta (412): Dressing change scheduled for 15:30 PM.',
  ],
  concernsObserved: [
    'Mrs. Malti Rao (408): Mild postural dizziness noted at 12:05 PM. Kept hydrated.',
  ],
  escalationsMade: [
    'Daughter Priya Sharma informed at 09:00 AM regarding Thursday cardiology appointment logistics.',
  ],
  isSignedOut: false,
};

export const initialAuditEvents: AuditEvent[] = [
  {
    id: 'aud-01',
    timestamp: '2026-09-15T08:32:00Z',
    actorName: 'Kavita Sharma',
    actorRole: 'OLDER_ADULT',
    action: 'MEDICATION_TAKEN',
    details: 'Marked Amlodipine 5mg as taken',
  },
  {
    id: 'aud-02',
    timestamp: '2026-09-15T08:00:00Z',
    actorName: 'Kavita Sharma',
    actorRole: 'OLDER_ADULT',
    action: 'CHECK_IN_COMPLETED',
    details: 'Completed daily check-in: Feeling Good 😊',
  },
  {
    id: 'aud-03',
    timestamp: '2026-09-15T07:45:00Z',
    actorName: 'Priya Sharma',
    actorRole: 'FAMILY_MEMBER',
    action: 'ROLE_SWITCHED',
    details: 'Sent morning voice message to parent',
  },
];
